services:
  postgres:
    image: postgres:16.3
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_DB: ${PG_DATABASE} 
    ports:
      - "${PG_PORT}:${PG_PORT}"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${PG_USERNAME}"]
      interval: 10s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - service_healthy_net

  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://${PG_USERNAME}:${PG_PASSWORD}@postgres:${PG_PORT}/${PG_DATABASE}
    command: ["sh", "-c", "wait-for-it.sh postgres:5432 -- alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 80"]
    volumes:
      - app-data:/app
    networks:
      - service_healthy_net

volumes:
  postgres_data:
  app-data:
    driver: local

networks:
  service_healthy_net: