services:
  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_DB: health_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:example@postgres:5432/health_tracker
    volumes:
      - app-data:/app

volumes:
  postgres_data:
  app-data:
    driver: local
