"""added avatar field to user

Revision ID: 7facd45ed00c
Revises: 7412af1e26ea
Create Date: 2024-09-20 18:59:26.929187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7facd45ed00c'
down_revision: Union[str, None] = '7412af1e26ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'phone_verification', ['id'])
    op.add_column('user', sa.Column('avatar_hex', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_hex')
    op.drop_constraint(None, 'phone_verification', type_='unique')
    # ### end Alembic commands ###
